### ISSUE TITLE
Patching drivers prevents encoding

### ISSUE THREAD

**Issue by ObjectionTheory** [keylase/nvidia-patch#230] opened 2020-01-26 23:20 UTC
Hello,

I have written a small dll application which uses NVENCODEAPI to encode D3D11Texture2Ds into H264. It was originally working fine and produced a valid output; however, after patching NvencodeAPI64.dll and NvencodeAPI.dll, the nvEncEncodePicture function now consistently throws an error 8: Invalid parameter. Now, reverting the patch by inverting the 1334 file does bring back the encoder limit but doesn't bring back the original functionality of being able to encode. Reinstalling drivers also has not worked. Has this been encountered by anyone so far? I am even hesitant to suggest that the patch broke the code, as it doesn't seem to contain anything that would exclusively interfere with encoding frames (initialising the encoder works fine). However, since the only change before the encoder stopped encoding was patching the dll, and as such I am asking here. 

I am running Windows 10 with a GTX 1080Ti card, with 441.87 drivers.

Patch used:
![image](https://user-images.githubusercontent.com/24833216/73143487-6d37d580-4092-11ea-8659-077a1600a2b6.png)

**Comment by Snawoot** [comment] 2020-01-27 00:13
Hello, @ObjectionTheory 

> It was originally working fine and produced a valid output; however, after patching NvencodeAPI64.dll and NvencodeAPI.dll, the nvEncEncodePicture function now consistently throws an error 8: Invalid parameter.

Every patch version gets manually tested and it's unlikely issues with your code caused by patch. You can assure yourself testing it with [ffmpeg](http://ffmpeg.org/download.html) (ffmpeg's `h264_nvenc` codec also uses nvEncEncodePicture, except it initializes encoding device with CUDA type).

> Now, reverting the patch by inverting the 1334 file does bring back the encoder limit but doesn't bring back the original functionality of being able to encode. Reinstalling drivers also has not worked.

So, basically, all patch is changing is 4 bytes in `NvencodeAPI64.dll` and 5 bytes `NvencodeAPI.dll`. You reverted it and nothing changed except limit. It actually confirms patch has nothing to do with error `error 8: Invalid parameter.` you get.

From my point of view your problem hardly connected with this project, it looks like plain API invocation error which for some reason didn't appeared before in other circumstances. I'm closing this issue, but if there will be some evidence problem really exists issue will be reopened. However, there are few steps you can take:
1. Test NVENC with FFmpeg: [link](https://trac.ffmpeg.org/wiki/HWAccelIntro#NVENC). Compilation steps are not needed if you downloaded binary build from [here](https://ffmpeg.zeranoe.com/builds/).
2. Try building and running examples from Nvidia Video Codec API SDK. I'm pretty sure they contain examples for all major usage scenarios.
3. If you believe there is still some problem with patch, then please leave us an opportunity to confirm and (most important) to reproduce it. Some minimal code which works w/o patch and doesn't w/ patch will do.

**Closed by Snawoot** 2020-01-27 00:13 UTC
Labels: question
