### ISSUE TITLE
New driver support (version 520.56.06)

### ISSUE THREAD

**Issue by troykelly** [keylase/nvidia-patch#571] opened 2022-10-07 01:23 UTC
**Please provide details about your environment (please complete the following information)**
- ~~Nvidia driver version: 520.61.05~~
- Required for 520.61.05 (Bundled [CUDA](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=runfile_local))
- Nvidia driver version 520.56.06 - @jailuthra 
- GPU Model: NVIDIA GeForce RTX 2060 SUPER, NVIDIA GeForce GTX 1660 Ti
- OS: Ubuntu 22.04
- [x] I'm willing to participate in testing of new patch version

**Comment by troykelly** [comment] 2022-10-07 01:24
Have tested the same patch for 515.76, but that does not work
```text
    ["515.76"]='s/\xe8\xd5\x1e\xff\xff\x85\xc0\x41\x89\xc4/\xe8\xd5\x1e\xff\xff\x29\xc0\x41\x89\xc4/g'
```

**Comment by mirolm** [comment] 2022-10-12 16:05
I can second that - the patch does not work with 520.56.06 driver.

**Comment by Strykar** [comment] 2022-10-14 08:07
Will this version (`520.56.06`) not be supported?

**Comment by jailuthra** [comment] 2022-10-15 07:57
Won't fix 520.61.05 as that is already out of date https://github.com/NVIDIA/open-gpu-kernel-modules/releases

Found the new bytecode for latest release (520.56.06) instead - Please test #574

**Comment by troykelly** [comment] 2022-10-15 09:37
@jailuthra Would it be possible to reconsider the `wontfix`?
The version requested here is the bundled version from the [CUDA toolkit](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=runfile_local).

**Comment by jailuthra** [comment] 2022-10-15 10:49
@troykelly if the bytecode is same then sure I can add support for the cuda toolkit version as well. I'm 99% sure it is the same (found the exact sequence via grep), but please test and let me know - or send a PR :)

**Comment by troykelly** [comment] 2022-10-15 10:51
Is the assumption that `520.61.05` will use the same as `520.56.06`?

**Comment by jailuthra** [comment] 2022-10-15 10:52
Not just an assumption, I see the exact sequence of bytes for the function that limits nvenc sessions in both these versions. Just need someone to try running the patch.sh and confirm it works (instructions to test are in the wiki)

**Comment by jailuthra** [comment] 2022-10-15 12:17
FYI I've updated the existing PR with both versions.

**Comment by mirolm** [comment] 2022-10-15 19:07
Checked 520.61.05 nvenc and it works as intended. Cannot check the fbc patch tho.

**Closed** 2022-10-16 03:31 UTC
Labels: enhancement
