### ISSUE TITLE
Screen Tearing when a app uses NVFBC

### ISSUE THREAD

**Issue by zany130** [keylase/nvidia-patch#466] opened 2021-11-17 16:29 UTC
**Describe the bug**
Screen Tearing when a app uses NVFBC

**To Reproduce**
1. apply the NVFBC patch
2. install obs-nvfbc or gpu-screen-recorder-gtk
3. record
4.  notice tearing

**Expected behavior**
obs or gpu-screen-recorder is able to record gameplay with minimal performance hit (it does) and no screen tearing

**Environment (please complete the following information):**
 - OS: [Garuda Linux]
 - GPU model: [ GTX 1080]
 - Patch commit used: [fe0c10b616b1b66dbc2b9a563705342200bef1c5]
 - Nvidia driver version: [e.g. 495.44-3]

**Comment by jailuthra** [comment] 2021-11-18 12:32
Is this a bug with the patch, or NVFBC driver itself?

**Comment by zany130** [comment] 2021-11-18 14:45
I have no clue. I have spoken to others who are able to use this without issues on 495 with obs-nvfbc while for me i get tearing whenever a recording app (OBS or GPU screen recorder) uses NVFB. Exiting the app immediately fixes the tearing

**Comment by zany130** [comment] 2021-11-20 00:34
update on this. I noticed I am getting Unable to cleanup NvFBC
message in obs logs which might be related I opened an issue also with https://gitlab.com/fzwoch/obs-nvfbc/-/issues/5
This was about a memleak though which might be unrelated (I think it was happening because I added obs-websokets)

**Comment by jailuthra** [comment] 2022-02-11 10:41
Closing as this wasn't caused by the patch.

**Closed by jailuthra** 2022-02-11 10:41 UTC
Labels: bug
